// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

package p2p

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageData struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	NodeId               string   `protobuf:"bytes,4,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *MessageData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type UploadQueryRequest struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Path                 string       `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64        `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadQueryRequest) Reset()         { *m = UploadQueryRequest{} }
func (m *UploadQueryRequest) String() string { return proto.CompactTextString(m) }
func (*UploadQueryRequest) ProtoMessage()    {}
func (*UploadQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1}
}

func (m *UploadQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadQueryRequest.Unmarshal(m, b)
}
func (m *UploadQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadQueryRequest.Marshal(b, m, deterministic)
}
func (m *UploadQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadQueryRequest.Merge(m, src)
}
func (m *UploadQueryRequest) XXX_Size() int {
	return xxx_messageInfo_UploadQueryRequest.Size(m)
}
func (m *UploadQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadQueryRequest proto.InternalMessageInfo

func (m *UploadQueryRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *UploadQueryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *UploadQueryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadQueryRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type UploadQueryResponse struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Tag                  string       `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Confirm              bool         `protobuf:"varint,3,opt,name=confirm,proto3" json:"confirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadQueryResponse) Reset()         { *m = UploadQueryResponse{} }
func (m *UploadQueryResponse) String() string { return proto.CompactTextString(m) }
func (*UploadQueryResponse) ProtoMessage()    {}
func (*UploadQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2}
}

func (m *UploadQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadQueryResponse.Unmarshal(m, b)
}
func (m *UploadQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadQueryResponse.Marshal(b, m, deterministic)
}
func (m *UploadQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadQueryResponse.Merge(m, src)
}
func (m *UploadQueryResponse) XXX_Size() int {
	return xxx_messageInfo_UploadQueryResponse.Size(m)
}
func (m *UploadQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadQueryResponse proto.InternalMessageInfo

func (m *UploadQueryResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *UploadQueryResponse) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *UploadQueryResponse) GetConfirm() bool {
	if m != nil {
		return m.Confirm
	}
	return false
}

type UploadRequest struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Tag                  string       `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Data                 []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{3}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *UploadRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *UploadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadResponse struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Tag                  string       `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Hash                 string       `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{4}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *UploadResponse) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *UploadResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type OperationSignatureRequest struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Tag                  string       `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	OperationSignature   []byte       `protobuf:"bytes,3,opt,name=operationSignature,proto3" json:"operationSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OperationSignatureRequest) Reset()         { *m = OperationSignatureRequest{} }
func (m *OperationSignatureRequest) String() string { return proto.CompactTextString(m) }
func (*OperationSignatureRequest) ProtoMessage()    {}
func (*OperationSignatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{5}
}

func (m *OperationSignatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationSignatureRequest.Unmarshal(m, b)
}
func (m *OperationSignatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationSignatureRequest.Marshal(b, m, deterministic)
}
func (m *OperationSignatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationSignatureRequest.Merge(m, src)
}
func (m *OperationSignatureRequest) XXX_Size() int {
	return xxx_messageInfo_OperationSignatureRequest.Size(m)
}
func (m *OperationSignatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationSignatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperationSignatureRequest proto.InternalMessageInfo

func (m *OperationSignatureRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *OperationSignatureRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *OperationSignatureRequest) GetOperationSignature() []byte {
	if m != nil {
		return m.OperationSignature
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageData)(nil), "protocols.p2p.MessageData")
	proto.RegisterType((*UploadQueryRequest)(nil), "protocols.p2p.UploadQueryRequest")
	proto.RegisterType((*UploadQueryResponse)(nil), "protocols.p2p.UploadQueryResponse")
	proto.RegisterType((*UploadRequest)(nil), "protocols.p2p.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "protocols.p2p.UploadResponse")
	proto.RegisterType((*OperationSignatureRequest)(nil), "protocols.p2p.OperationSignatureRequest")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x95, 0x26, 0x7f, 0x7f, 0x32, 0xa5, 0x15, 0x32, 0x12, 0x32, 0x88, 0x45, 0x95, 0x55,
	0x57, 0x59, 0x94, 0x2d, 0x4b, 0x36, 0x08, 0x21, 0x84, 0x11, 0x07, 0x70, 0x9b, 0xa1, 0xb5, 0xd4,
	0xd8, 0x26, 0x76, 0x90, 0xca, 0x86, 0x1b, 0x70, 0x01, 0x4e, 0xc0, 0x2d, 0x91, 0xa7, 0x09, 0x6d,
	0x55, 0x76, 0xd0, 0x55, 0xde, 0xbc, 0x49, 0x3c, 0xef, 0x1b, 0x07, 0x52, 0x3b, 0xb6, 0xb9, 0xad,
	0x8c, 0x37, 0xac, 0x4f, 0x8f, 0xa9, 0x59, 0xb8, 0xdc, 0x8e, 0x6d, 0xf6, 0x19, 0x41, 0xef, 0x16,
	0x9d, 0x93, 0x33, 0xbc, 0x92, 0x5e, 0x32, 0x0e, 0xff, 0x5f, 0xb0, 0x72, 0xca, 0x68, 0x1e, 0x0d,
	0xa3, 0x51, 0x2a, 0xda, 0x92, 0x9d, 0x43, 0xea, 0x55, 0x89, 0xce, 0xcb, 0xd2, 0xf2, 0xce, 0x30,
	0x1a, 0xc5, 0x62, 0x6d, 0xb0, 0x01, 0x74, 0x54, 0xc1, 0x63, 0xfa, 0xa4, 0xa3, 0x0a, 0x76, 0x02,
	0x5d, 0x6d, 0x0a, 0xbc, 0x2e, 0x78, 0x42, 0x5e, 0x53, 0x85, 0x53, 0x6c, 0x3d, 0x59, 0xa8, 0xe9,
	0x0d, 0x2e, 0xf9, 0xbf, 0x61, 0x34, 0x3a, 0x14, 0x6b, 0x23, 0x74, 0x9d, 0x9a, 0x69, 0xe9, 0xeb,
	0x0a, 0x79, 0x77, 0xd5, 0xfd, 0x36, 0xb2, 0xf7, 0x08, 0xd8, 0xa3, 0x5d, 0x18, 0x59, 0xdc, 0xd7,
	0x58, 0x2d, 0x05, 0x3e, 0xd7, 0xe8, 0x3c, 0xbb, 0x84, 0x5e, 0xb9, 0x26, 0xa0, 0xd8, 0xbd, 0xf1,
	0x59, 0xbe, 0xc5, 0x99, 0x6f, 0x30, 0x8a, 0xcd, 0xd7, 0x19, 0x83, 0xc4, 0x4a, 0x3f, 0x27, 0xa2,
	0x54, 0x90, 0x0e, 0x9e, 0x96, 0x25, 0x36, 0x38, 0xa4, 0x83, 0xe7, 0xd4, 0x2b, 0x12, 0x4e, 0x2c,
	0x48, 0x67, 0x6f, 0x70, 0xbc, 0x95, 0xc7, 0x59, 0xa3, 0x1d, 0xfe, 0x32, 0xd0, 0x11, 0xc4, 0x5e,
	0xce, 0x9a, 0x3c, 0x41, 0x86, 0x3b, 0x99, 0x1a, 0xfd, 0xa4, 0xaa, 0x92, 0x12, 0x1d, 0x88, 0xb6,
	0xcc, 0x1c, 0xf4, 0x57, 0x01, 0xfe, 0x66, 0x17, 0xbb, 0xa3, 0x19, 0x24, 0x45, 0x38, 0x28, 0xa6,
	0xbb, 0x20, 0x9d, 0x79, 0x18, 0xb4, 0x43, 0xf7, 0x04, 0xcc, 0x20, 0x99, 0x4b, 0x37, 0x6f, 0xf7,
	0x1f, 0x74, 0xf6, 0x11, 0xc1, 0xe9, 0x9d, 0xc5, 0x4a, 0x7a, 0x65, 0xf4, 0x43, 0xfb, 0x4f, 0xec,
	0x8b, 0x3b, 0x07, 0x66, 0x76, 0x86, 0x35, 0x5b, 0xf8, 0xa1, 0x33, 0xe9, 0xd2, 0xa4, 0x8b, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0x65, 0x76, 0x7e, 0x69, 0x03, 0x00, 0x00,
}
