// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

package p2p

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// designed to be shared between all app protocols
type MessageData struct {
	// shared between all requests
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Gossip               bool     `protobuf:"varint,4,opt,name=gossip,proto3" json:"gossip,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type UploadQueryRequest struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Path                 string       `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64        `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadQueryRequest) Reset()         { *m = UploadQueryRequest{} }
func (m *UploadQueryRequest) String() string { return proto.CompactTextString(m) }
func (*UploadQueryRequest) ProtoMessage()    {}
func (*UploadQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1}
}

func (m *UploadQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadQueryRequest.Unmarshal(m, b)
}
func (m *UploadQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadQueryRequest.Marshal(b, m, deterministic)
}
func (m *UploadQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadQueryRequest.Merge(m, src)
}
func (m *UploadQueryRequest) XXX_Size() int {
	return xxx_messageInfo_UploadQueryRequest.Size(m)
}
func (m *UploadQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadQueryRequest proto.InternalMessageInfo

func (m *UploadQueryRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *UploadQueryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *UploadQueryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadQueryRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type UploadQueryResponse struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Tag                  string       `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Address              string       `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadQueryResponse) Reset()         { *m = UploadQueryResponse{} }
func (m *UploadQueryResponse) String() string { return proto.CompactTextString(m) }
func (*UploadQueryResponse) ProtoMessage()    {}
func (*UploadQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2}
}

func (m *UploadQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadQueryResponse.Unmarshal(m, b)
}
func (m *UploadQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadQueryResponse.Marshal(b, m, deterministic)
}
func (m *UploadQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadQueryResponse.Merge(m, src)
}
func (m *UploadQueryResponse) XXX_Size() int {
	return xxx_messageInfo_UploadQueryResponse.Size(m)
}
func (m *UploadQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadQueryResponse proto.InternalMessageInfo

func (m *UploadQueryResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *UploadQueryResponse) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *UploadQueryResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UploadRequest struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Tag                  string       `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Data                 []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{3}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *UploadRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *UploadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadResponse struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Tag                  string       `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Hash                 string       `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{4}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *UploadResponse) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *UploadResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type OperationSignatureRequest struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Tag                  string       `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	OperationSignature   []byte       `protobuf:"bytes,3,opt,name=operationSignature,proto3" json:"operationSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OperationSignatureRequest) Reset()         { *m = OperationSignatureRequest{} }
func (m *OperationSignatureRequest) String() string { return proto.CompactTextString(m) }
func (*OperationSignatureRequest) ProtoMessage()    {}
func (*OperationSignatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{5}
}

func (m *OperationSignatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationSignatureRequest.Unmarshal(m, b)
}
func (m *OperationSignatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationSignatureRequest.Marshal(b, m, deterministic)
}
func (m *OperationSignatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationSignatureRequest.Merge(m, src)
}
func (m *OperationSignatureRequest) XXX_Size() int {
	return xxx_messageInfo_OperationSignatureRequest.Size(m)
}
func (m *OperationSignatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationSignatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperationSignatureRequest proto.InternalMessageInfo

func (m *OperationSignatureRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *OperationSignatureRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *OperationSignatureRequest) GetOperationSignature() []byte {
	if m != nil {
		return m.OperationSignature
	}
	return nil
}

type DownloadRequest struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Hash                 string       `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{6}
}

func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (m *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(m, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

func (m *DownloadRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *DownloadRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type DownloadResponse struct {
	MessageData          *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Hash                 string       `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Data                 []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DownloadResponse) Reset()         { *m = DownloadResponse{} }
func (m *DownloadResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadResponse) ProtoMessage()    {}
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{7}
}

func (m *DownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResponse.Unmarshal(m, b)
}
func (m *DownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResponse.Marshal(b, m, deterministic)
}
func (m *DownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResponse.Merge(m, src)
}
func (m *DownloadResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadResponse.Size(m)
}
func (m *DownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResponse proto.InternalMessageInfo

func (m *DownloadResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *DownloadResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *DownloadResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageData)(nil), "p2p.MessageData")
	proto.RegisterType((*UploadQueryRequest)(nil), "p2p.UploadQueryRequest")
	proto.RegisterType((*UploadQueryResponse)(nil), "p2p.UploadQueryResponse")
	proto.RegisterType((*UploadRequest)(nil), "p2p.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "p2p.UploadResponse")
	proto.RegisterType((*OperationSignatureRequest)(nil), "p2p.OperationSignatureRequest")
	proto.RegisterType((*DownloadRequest)(nil), "p2p.DownloadRequest")
	proto.RegisterType((*DownloadResponse)(nil), "p2p.DownloadResponse")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xd1, 0xca, 0xd3, 0x30,
	0x14, 0xc7, 0x49, 0x5b, 0xf7, 0xd9, 0x33, 0xbf, 0x39, 0x22, 0x48, 0x04, 0x91, 0x52, 0xbc, 0xe8,
	0xd5, 0x2e, 0xea, 0x2b, 0xec, 0x46, 0x44, 0xd4, 0x88, 0x82, 0x97, 0x99, 0x39, 0x74, 0x91, 0x35,
	0x89, 0x4d, 0x8a, 0xcc, 0x6b, 0x5f, 0xc0, 0x87, 0xf2, 0xbd, 0x24, 0x59, 0xcb, 0x3a, 0xb6, 0xab,
	0x6f, 0xbb, 0xfb, 0x9f, 0x93, 0xe4, 0x9c, 0xff, 0xef, 0x5f, 0x28, 0xe4, 0xb6, 0xb6, 0x2b, 0xdb,
	0x19, 0x6f, 0x68, 0x6a, 0x6b, 0x5b, 0xfe, 0x23, 0x30, 0x7f, 0x8f, 0xce, 0x89, 0x06, 0xd7, 0xc2,
	0x0b, 0xfa, 0x1a, 0xee, 0xbf, 0xef, 0x14, 0x6a, 0xff, 0x15, 0x3b, 0xa7, 0x8c, 0x66, 0xa4, 0x20,
	0x55, 0xce, 0x4f, 0x9b, 0xf4, 0x25, 0xe4, 0x5e, 0xb5, 0xe8, 0xbc, 0x68, 0x2d, 0x4b, 0x0a, 0x52,
	0xa5, 0xfc, 0xd8, 0xa0, 0x0b, 0x48, 0x94, 0x64, 0x69, 0x7c, 0x98, 0x28, 0x49, 0x9f, 0xc3, 0xac,
	0x31, 0xce, 0x29, 0xcb, 0xb2, 0x82, 0x54, 0x8f, 0xf9, 0x50, 0x85, 0xbe, 0x36, 0x12, 0xdf, 0x4a,
	0xf6, 0x28, 0xde, 0x1d, 0x2a, 0xfa, 0x0a, 0x20, 0xa8, 0x8f, 0xfd, 0xe6, 0x1d, 0xee, 0xd9, 0xac,
	0x20, 0xd5, 0x13, 0x3e, 0xe9, 0x50, 0x0a, 0x99, 0x53, 0x8d, 0x66, 0x77, 0xf1, 0x24, 0xea, 0xf2,
	0x0f, 0x01, 0xfa, 0xc5, 0xee, 0x8c, 0x90, 0x9f, 0x7a, 0xec, 0xf6, 0x1c, 0x7f, 0xf6, 0xe8, 0x3c,
	0xad, 0x61, 0xde, 0x1e, 0xe9, 0x22, 0xcc, 0xbc, 0x5e, 0xae, 0x42, 0x08, 0x13, 0x6a, 0x3e, 0xbd,
	0x14, 0xc6, 0x5b, 0xe1, 0xb7, 0x91, 0x2b, 0xe7, 0x51, 0x87, 0x9e, 0x16, 0x2d, 0x0e, 0x50, 0x51,
	0x1f, 0x6c, 0xfc, 0xc6, 0x08, 0x95, 0xf2, 0xa8, 0xcb, 0x1e, 0x9e, 0x9d, 0xb8, 0x70, 0xd6, 0x68,
	0x87, 0x0f, 0xb2, 0xb1, 0x84, 0xd4, 0x8b, 0x66, 0x70, 0x11, 0x24, 0x65, 0x70, 0x27, 0xa4, 0xec,
	0xd0, 0xb9, 0xc1, 0xc7, 0x58, 0x96, 0x0a, 0xee, 0x0f, 0x6b, 0xaf, 0xe1, 0x3e, 0x5f, 0x48, 0x21,
	0x93, 0xe1, 0x79, 0x7a, 0x08, 0x3a, 0xe8, 0xf2, 0x07, 0x2c, 0xc6, 0x55, 0x37, 0x85, 0xa3, 0x90,
	0x6d, 0x85, 0xdb, 0x8e, 0x09, 0x07, 0x5d, 0xfe, 0x25, 0xf0, 0xe2, 0x83, 0xc5, 0x4e, 0x78, 0x65,
	0xf4, 0x67, 0xd5, 0x68, 0xe1, 0xfb, 0x0e, 0x6f, 0xcb, 0xb8, 0x02, 0x6a, 0xce, 0x56, 0x0c, 0xc4,
	0x17, 0x4e, 0xca, 0x6f, 0xf0, 0x74, 0x6d, 0x7e, 0xe9, 0x6b, 0xc3, 0x1e, 0x71, 0x93, 0x09, 0xae,
	0x86, 0xe5, 0x71, 0xf4, 0x15, 0xe1, 0x5e, 0x98, 0x7d, 0xe9, 0x53, 0x6e, 0x66, 0xf1, 0x3f, 0xf0,
	0xe6, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x2b, 0xf2, 0x1e, 0x14, 0x04, 0x00, 0x00,
}
